### PR TITLE
fix typo,"read-type-from-daraId" to "read-type-from-dataId"

### PR DESCRIPTION
**Pull request by liaozan**
#246

### CODE REVIEW

**Review by KeRan213539 — CHANGES_REQUESTED** [review]
This property will be removed. Please see #247

**Review by KeRan213539 — CHANGES_REQUESTED** [review]
This property will be removed. Please see #247

**Comment by liaozan** [comment]
got it

**Comment by KeRan213539** [comment]
Thank you for your contribution, you can look at other issues to modify  :)

**Pull request closed without merging**
